In [70]:
import pandas as pd

In [71]:
file1 = 'JC-201801-citibike-tripdata.csv'

In [72]:
df1 = pd.read_csv(file)

In [73]:
print(df1).head

       tripduration                 starttime                  stoptime  \
0               932  2018-01-01 02:06:17.5410  2018-01-01 02:21:50.0270
1               550  2018-01-01 12:06:18.0390  2018-01-01 12:15:28.4430
2               510  2018-01-01 12:06:56.9780  2018-01-01 12:15:27.8100
3               354  2018-01-01 14:53:10.1860  2018-01-01 14:59:05.0960
4               250  2018-01-01 17:34:30.1920  2018-01-01 17:38:40.9840
5               613  2018-01-01 22:05:05.8740  2018-01-01 22:15:19.4190
6               290  2018-01-02 12:13:51.7940  2018-01-02 12:18:42.1070
7               381  2018-01-02 12:50:03.3430  2018-01-02 12:56:24.6440
8               318  2018-01-02 13:55:58.2430  2018-01-02 14:01:16.8810
9              1852  2018-01-02 16:55:29.6390  2018-01-02 17:26:22.3050
10              460  2018-01-02 17:01:50.5860  2018-01-02 17:09:31.4340
11              403  2018-01-02 17:05:12.2360  2018-01-02 17:11:55.2630
12              264  2018-01-02 17:05:12.6730  2018-01-02 17:09:37.4020
13              282  2018-01-02 17:19:56.6090  2018-01-02 17:24:39.5340
14              308  2018-01-02 17:31:45.9880  2018-01-02 17:36:54.3590
15              561  2018-01-02 17:32:54.8400  2018-01-02 17:42:16.3140
16              114  2018-01-02 17:37:44.3450  2018-01-02 17:39:38.8760
17              302  2018-01-02 17:54:04.8770  2018-01-02 17:59:06.9730
18              230  2018-01-02 17:58:24.6360  2018-01-02 18:02:15.6320
19              596  2018-01-02 18:05:59.6240  2018-01-02 18:15:55.8590
20              826  2018-01-02 18:10:58.8600  2018-01-02 18:24:45.1600
21              368  2018-01-02 18:13:41.8510  2018-01-02 18:19:49.9780
22              291  2018-01-02 18:18:41.6860  2018-01-02 18:23:33.0620
23              250  2018-01-02 18:20:06.1050  2018-01-02 18:24:16.1640
24              199  2018-01-02 18:31:11.9870  2018-01-02 18:34:31.1880
25              225  2018-01-02 18:38:50.5100  2018-01-02 18:42:36.2120
26              242  2018-01-02 18:41:29.5240  2018-01-02 18:45:32.3240
27              214  2018-01-02 18:42:30.3030  2018-01-02 18:46:04.4630
28              218  2018-01-02 19:29:20.7870  2018-01-02 19:32:59.1490
29              318  2018-01-02 19:30:19.4880  2018-01-02 19:35:37.5450
...             ...                       ...                       ...
12647           413  2018-01-25 18:06:50.9210  2018-01-25 18:13:44.1630
12648           310  2018-01-25 20:28:29.4960  2018-01-25 20:33:39.5260
12649           317  2018-01-26 12:52:34.3540  2018-01-26 12:57:52.1050
12650           434  2018-01-26 18:27:50.6100  2018-01-26 18:35:05.6020
12651           302  2018-01-26 18:57:41.8890  2018-01-26 19:02:43.9920
12652           466  2018-01-26 19:01:58.3660  2018-01-26 19:09:44.9850
12653           394  2018-01-26 19:04:31.7650  2018-01-26 19:11:05.8360
12654           431  2018-01-26 20:24:13.5210  2018-01-26 20:31:25.2090
12655           638  2018-01-26 20:52:48.3140  2018-01-26 21:03:26.9960
12656           250  2018-01-26 21:25:35.4710  2018-01-26 21:29:45.6490
12657           231  2018-01-26 21:25:41.0140  2018-01-26 21:29:32.2930
12658           553  2018-01-26 22:32:38.8040  2018-01-26 22:41:51.8230
12659           336  2018-01-27 13:09:07.9730  2018-01-27 13:14:44.1090
12660           635  2018-01-27 20:51:38.1560  2018-01-27 21:02:13.7790
12661           355  2018-01-28 19:14:38.0160  2018-01-28 19:20:33.7500
12662           557  2018-01-28 20:51:08.9220  2018-01-28 21:00:26.4300
12663           235  2018-01-29 10:15:18.1610  2018-01-29 10:19:13.2110
12664           364  2018-01-29 13:53:57.2300  2018-01-29 14:00:01.5470
12665           294  2018-01-29 17:41:14.5210  2018-01-29 17:46:08.8440
12666           365  2018-01-29 18:00:05.8960  2018-01-29 18:06:11.7330
12667           705  2018-01-30 16:34:20.0470  2018-01-30 16:46:05.7640
12668           491  2018-01-30 17:30:26.4000  2018-01-30 17:38:38.3360
12669           284  2018-01-30 18:58:19.0490  2018-01-30 19:03:04.0060
12670           265  2018-01-30 21:25:14.8410  2018-01-30 21:29:40.5050
12671           266  2018-01-31 11:03:40.7660  2018-01-31 11:08:06.8270
12672           247  2018-01-31 11:03:59.1750  2018-01-31 11:08:07.0570
12673           806  2018-01-31 15:34:36.8370  2018-01-31 15:48:03.0280
12674          1499  2018-01-31 15:45:09.8000  2018-01-31 16:10:09.4400
12675           291  2018-01-31 16:54:11.9480  2018-01-31 16:59:03.5760
12676           383  2018-01-31 18:34:50.2950  2018-01-31 18:41:13.7530

       start station id start station name  start station latitude  \
0                  3183     Exchange Place               40.716247
1                  3183     Exchange Place               40.716247
2                  3183     Exchange Place               40.716247
3                  3183     Exchange Place               40.716247
4                  3183     Exchange Place               40.716247
5                  3183     Exchange Place               40.716247
6                  3183     Exchange Place               40.716247
7                  3183     Exchange Place               40.716247
8                  3183     Exchange Place               40.716247
9                  3183     Exchange Place               40.716247
10                 3183     Exchange Place               40.716247
11                 3183     Exchange Place               40.716247
12                 3183     Exchange Place               40.716247
13                 3183     Exchange Place               40.716247
14                 3183     Exchange Place               40.716247
15                 3183     Exchange Place               40.716247
16                 3183     Exchange Place               40.716247
17                 3183     Exchange Place               40.716247
18                 3183     Exchange Place               40.716247
19                 3183     Exchange Place               40.716247
20                 3183     Exchange Place               40.716247
21                 3183     Exchange Place               40.716247
22                 3183     Exchange Place               40.716247
23                 3183     Exchange Place               40.716247
24                 3183     Exchange Place               40.716247
25                 3183     Exchange Place               40.716247
26                 3183     Exchange Place               40.716247
27                 3183     Exchange Place               40.716247
28                 3183     Exchange Place               40.716247
29                 3183     Exchange Place               40.716247
...                 ...                ...                     ...
12647              3640     Journal Square               40.733670
12648              3640     Journal Square               40.733670
12649              3640     Journal Square               40.733670
12650              3640     Journal Square               40.733670
12651              3640     Journal Square               40.733670
12652              3640     Journal Square               40.733670
12653              3640     Journal Square               40.733670
12654              3640     Journal Square               40.733670
12655              3640     Journal Square               40.733670
12656              3640     Journal Square               40.733670
12657              3640     Journal Square               40.733670
12658              3640     Journal Square               40.733670
12659              3640     Journal Square               40.733670
12660              3640     Journal Square               40.733670
12661              3640     Journal Square               40.733670
12662              3640     Journal Square               40.733670
12663              3640     Journal Square               40.733670
12664              3640     Journal Square               40.733670
12665              3640     Journal Square               40.733670
12666              3640     Journal Square               40.733670
12667              3640     Journal Square               40.733670
12668              3640     Journal Square               40.733670
12669              3640     Journal Square               40.733670
12670              3640     Journal Square               40.733670
12671              3640     Journal Square               40.733670
12672              3640     Journal Square               40.733670
12673              3640     Journal Square               40.733670
12674              3640     Journal Square               40.733670
12675              3640     Journal Square               40.733670
12676              3640     Journal Square               40.733670

       start station longitude  end station id       end station name  \
0                   -74.033459            3199           Newport Pkwy
1                   -74.033459            3199           Newport Pkwy
2                   -74.033459            3199           Newport Pkwy
3                   -74.033459            3267           Morris Canal
4                   -74.033459            3639             Harborside
5                   -74.033459            3203          Hamilton Park
6                   -74.033459            3267           Morris Canal
7                   -74.033459            3205      JC Medical Center
8                   -74.033459            3275         Columbus Drive
9                   -74.033459            3281    Leonard Gordon Park
10                  -74.033459            3199           Newport Pkwy
11                  -74.033459            3205      JC Medical Center
12                  -74.033459            3267           Morris Canal
13                  -74.033459            3267           Morris Canal
14                  -74.033459            3267           Morris Canal
15                  -74.033459            3269        Brunswick & 6th
16                  -74.033459            3639             Harborside
17                  -74.033459            3187              Warren St
18                  -74.033459            3267           Morris Canal
19                  -74.033459            3267           Morris Canal
20                  -74.033459            3194        McGinley Square
21                  -74.033459            3267           Morris Canal
22                  -74.033459            3187              Warren St
23                  -74.033459            3267           Morris Canal
24                  -74.033459            3267           Morris Canal
25                  -74.033459            3185              City Hall
26                  -74.033459            3267           Morris Canal
27                  -74.033459            3267           Morris Canal
28                  -74.033459            3267           Morris Canal
29                  -74.033459            3267           Morris Canal
...                        ...             ...                    ...
12647               -74.062500            3281    Leonard Gordon Park
12648               -74.062500            3207            Oakland Ave
12649               -74.062500            3207            Oakland Ave
12650               -74.062500            3281    Leonard Gordon Park
12651               -74.062500            3194        McGinley Square
12652               -74.062500            3210         Pershing Field
12653               -74.062500            3207            Oakland Ave
12654               -74.062500            3211             Newark Ave
12655               -74.062500            3280            Astor Place
12656               -74.062500            3201                 Dey St
12657               -74.062500            3201                 Dey St
12658               -74.062500            3210         Pershing Field
12659               -74.062500            3225  Baldwin at Montgomery
12660               -74.062500            3210         Pershing Field
12661               -74.062500            3194        McGinley Square
12662               -74.062500            3210         Pershing Field
12663               -74.062500            3201                 Dey St
12664               -74.062500            3207            Oakland Ave
12665               -74.062500            3207            Oakland Ave
12666               -74.062500            3281    Leonard Gordon Park
12667               -74.062500            3194        McGinley Square
12668               -74.062500            3281    Leonard Gordon Park
12669               -74.062500            3207            Oakland Ave
12670               -74.062500            3207            Oakland Ave
12671               -74.062500            3201                 Dey St
12672               -74.062500            3201                 Dey St
12673               -74.062500            3211             Newark Ave
12674               -74.062500            3640         Journal Square
12675               -74.062500            3201                 Dey St
12676               -74.062500            3194        McGinley Square

       end station latitude  end station longitude  bikeid    usertype  \
0                 40.728745             -74.032108   31929  Subscriber
1                 40.728745             -74.032108   31845  Subscriber
2                 40.728745             -74.032108   31708  Subscriber
3                 40.712419             -74.038526   31697  Subscriber
4                 40.719252             -74.034234   31861  Subscriber
5                 40.727596             -74.044247   31859  Subscriber
6                 40.712419             -74.038526   31694  Subscriber
7                 40.716540             -74.049638   31754  Subscriber
8                 40.718355             -74.038914   31816  Subscriber
9                 40.745910             -74.057271   31754  Subscriber
10                40.728745             -74.032108   33463  Subscriber
11                40.716540             -74.049638   26256  Subscriber
12                40.712419             -74.038526   29616  Subscriber
13                40.712419             -74.038526   29681  Subscriber
14                40.712419             -74.038526   31949  Subscriber
15                40.726012             -74.050389   29591  Subscriber
16                40.719252             -74.034234   31925  Subscriber
17                40.721124             -74.038051   31777  Subscriber
18                40.712419             -74.038526   31763  Subscriber
19                40.712419             -74.038526   29662  Subscriber
20                40.725340             -74.067622   31765  Subscriber
21                40.712419             -74.038526   31695  Subscriber
22                40.721124             -74.038051   31934  Subscriber
23                40.712419             -74.038526   31880  Subscriber
24                40.712419             -74.038526   29623  Subscriber
25                40.717733             -74.043845   31691  Subscriber
26                40.712419             -74.038526   26314  Subscriber
27                40.712419             -74.038526   29581  Subscriber
28                40.712419             -74.038526   31954  Subscriber
29                40.712419             -74.038526   29615  Subscriber
...                     ...                    ...     ...         ...
12647             40.745910             -74.057271   31829  Subscriber
12648             40.737604             -74.052478   31765  Subscriber
12649             40.737604             -74.052478   31765  Subscriber
12650             40.745910             -74.057271   26193  Subscriber
12651             40.725340             -74.067622   29587  Subscriber
12652             40.742677             -74.051789   31719  Subscriber
12653             40.737604             -74.052478   31728  Subscriber
12654             40.721525             -74.046305   31829  Subscriber
12655             40.719282             -74.071262   26289  Subscriber
12656             40.737711             -74.066921   31717  Subscriber
12657             40.737711             -74.066921   31925  Subscriber
12658             40.742677             -74.051789   29577  Subscriber
12659             40.723659             -74.064194   29581  Subscriber
12660             40.742677             -74.051789   32843  Subscriber
12661             40.725340             -74.067622   31777  Subscriber
12662             40.742677             -74.051789   29674  Subscriber
12663             40.737711             -74.066921   29644  Subscriber
12664             40.737604             -74.052478   31878  Subscriber
12665             40.737604             -74.052478   29622  Subscriber
12666             40.745910             -74.057271   31690  Subscriber
12667             40.725340             -74.067622   31870  Subscriber
12668             40.745910             -74.057271   29622  Subscriber
12669             40.737604             -74.052478   31861  Subscriber
12670             40.737604             -74.052478   26289  Subscriber
12671             40.737711             -74.066921   31841  Subscriber
12672             40.737711             -74.066921   31828  Subscriber
12673             40.721525             -74.046305   31842  Subscriber
12674             40.733670             -74.062500   29622  Subscriber
12675             40.737711             -74.066921   29622  Subscriber
12676             40.725340             -74.067622   31690  Subscriber

       birth year  gender
0            1992       1
1            1969       2
2            1946       1
3            1994       1
4            1991       1
5            1982       1
6            1958       1
7            1989       2
8            1960       1
9            1976       1
10           1989       2
11           1985       1
12           1974       1
13           1976       1
14           1968       1
15           1976       1
16           1988       1
17           1990       1
18           1992       1
19           1992       1
20           1989       1
21           1985       1
22           1980       1
23           1995       1
24           1980       1
25           1992       1
26           1981       0
27           1991       1
28           1991       1
29           1978       1
...           ...     ...
12647        1990       1
12648        1986       1
12649        1957       1
12650        1991       1
12651        1987       1
12652        1985       1
12653        1989       1
12654        1985       1
12655        1960       1
12656        1983       1
12657        1970       1
12658        1986       1
12659        1989       1
12660        1986       1
12661        1991       2
12662        1986       1
12663        1962       2
12664        1985       1
12665        1985       1
12666        1990       1
12667        1980       1
12668        1972       1
12669        1983       1
12670        1986       1
12671        1962       2
12672        1962       1
12673        1987       1
12674        1981       1
12675        1963       1
12676        1989       1

[12677 rows x 15 columns]

AttributeError: 'NoneType' object has no attribute 'head'

In [74]:
df1.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df1.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1

In [75]:
file2 = 'JC-201802-citibike-tripdata.csv'

In [76]:
df2 = pd.read_csv(file2)

In [77]:
df2.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df2.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,134,2018-02-01 07:38:15.8650,2018-02-01 07:40:30.5820,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29615,Subscriber,1966,1
1,413,2018-02-01 08:19:35.8160,2018-02-01 08:26:29.6490,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29641,Subscriber,1986,2
2,77,2018-02-01 08:31:03.0860,2018-02-01 08:32:20.3510,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29621,Subscriber,1975,1
3,404,2018-02-01 15:23:15.0850,2018-02-01 15:29:59.9300,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31934,Subscriber,1980,1
4,230,2018-02-01 15:26:01.8240,2018-02-01 15:29:52.5440,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,29642,Subscriber,1986,1

In [78]:
file3 = 'JC-201803-citibike-tripdata.csv'
df3 = pd.read_csv(file3)

In [79]:
df3.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df3.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,329,2018-03-01 06:37:37.0380,2018-03-01 06:43:06.5520,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29284,Subscriber,1981,1
1,118,2018-03-01 07:37:30.1210,2018-03-01 07:39:28.3910,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29465,Subscriber,1966,1
2,76,2018-03-01 08:26:17.9390,2018-03-01 08:27:34.6770,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29681,Subscriber,1975,1
3,578,2018-03-01 12:10:36.2160,2018-03-01 12:20:14.8690,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,31695,Subscriber,1970,1
4,485,2018-03-01 12:21:47.8800,2018-03-01 12:29:53.2990,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31802,Subscriber,1979,1

In [80]:
file4 = 'JC-201804-citibike-tripdata.csv'
df4 = pd.read_csv(file4)
df4.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df4.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1814,2018-04-01 09:43:51.1590,2018-04-01 10:14:06.1300,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,26175,Subscriber,1978,1
1,298,2018-04-01 11:42:53.7090,2018-04-01 11:47:51.8770,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31847,Subscriber,1979,1
2,1060,2018-04-01 12:43:11.9640,2018-04-01 13:00:52.8700,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,33463,Subscriber,1972,1
3,1035,2018-04-01 12:43:40.5890,2018-04-01 13:00:55.6620,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,31738,Subscriber,1983,1
4,559,2018-04-01 12:56:47.4600,2018-04-01 13:06:06.7710,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31925,Subscriber,1989,1

In [81]:
file5 = 'JC-201805-citibike-tripdata.csv'
df5 = pd.read_csv(file5)
df5.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df5.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,131,2018-05-01 07:29:57.5490,2018-05-01 07:32:08.6160,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29617,Subscriber,1966,1
1,73,2018-05-01 08:13:58.2560,2018-05-01 08:15:11.9230,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29288,Subscriber,1975,1
2,4929,2018-05-01 08:17:21.3110,2018-05-01 09:39:31.0770,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,29520,Customer,1969,0
3,432,2018-05-01 08:25:58.7150,2018-05-01 08:33:10.8960,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29595,Subscriber,1973,1
4,432,2018-05-01 08:28:09.9160,2018-05-01 08:35:22.1440,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,33623,Subscriber,1959,1

In [82]:
file6 = 'JC-201806-citibike-tripdata.csv'
df6 = pd.read_csv(file6)
df6.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df6.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,329,2018-06-01 07:07:00.2990,2018-06-01 07:12:30.2220,3183,Exchange Place,40.716247,-74.033459,3276,Marin Light Rail,40.714584,-74.042817,29513,Subscriber,1991,1
1,259,2018-06-01 08:24:43.8490,2018-06-01 08:29:03.8450,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26221,Subscriber,1989,2
2,686,2018-06-01 09:17:49.5730,2018-06-01 09:29:16.1770,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29266,Subscriber,1990,1
3,164,2018-06-01 09:44:00.4020,2018-06-01 09:46:44.6830,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29472,Subscriber,1993,1
4,769,2018-06-01 09:59:28.7800,2018-06-01 10:12:18.6660,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,33679,Subscriber,1977,1

In [83]:
file7 = 'JC-201807-citibike-tripdata.csv'
df7 = pd.read_csv(file7)
df7.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df7.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1234,2018-07-01 02:08:39.8920,2018-07-01 02:29:14.4890,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,26306,Customer,1969,0
1,1041,2018-07-01 02:09:07.5180,2018-07-01 02:26:28.8720,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,29204,Customer,1969,0
2,2308,2018-07-01 02:14:45.7400,2018-07-01 02:53:14.5970,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,26234,Customer,1969,0
3,767,2018-07-01 02:25:12.4020,2018-07-01 02:38:00.0510,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,26238,Subscriber,1992,1
4,151,2018-07-01 04:07:44.0520,2018-07-01 04:10:15.8010,3183,Exchange Place,40.716247,-74.033459,3275,Columbus Drive,40.718355,-74.038914,29204,Subscriber,1972,1

In [84]:
file8 = 'JC-201808-citibike-tripdata.csv'
df8 = pd.read_csv(file8)
df8.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df8.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,903,2018-08-01 06:40:33.3610,2018-08-01 06:55:37.1060,3183,Exchange Place,40.716247,-74.033459,3270,Jersey & 6th St,40.725289,-74.045572,29612,Subscriber,1977,1
1,78,2018-08-01 08:21:00.1450,2018-08-01 08:22:18.6310,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29791,Subscriber,1975,1
2,405,2018-08-01 08:43:52.5150,2018-08-01 08:50:37.6140,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29571,Subscriber,1973,1
3,155,2018-08-01 09:48:24.9450,2018-08-01 09:51:00.9360,3183,Exchange Place,40.716247,-74.033459,3275,Columbus Drive,40.718355,-74.038914,29504,Subscriber,1971,1
4,453,2018-08-01 12:15:35.1230,2018-08-01 12:23:08.8880,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,33669,Subscriber,1993,1

In [85]:
file9 = 'JC-201809-citibike-tripdata.csv'
df9 = pd.read_csv(file9)
df9.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df9.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,284,2018-09-01 01:48:22.0320,2018-09-01 01:53:06.9130,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26303,Subscriber,1984,1
1,370,2018-09-01 01:48:22.5010,2018-09-01 01:54:32.9270,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29667,Subscriber,1984,1
2,1181,2018-09-01 09:37:04.3070,2018-09-01 09:56:45.3280,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26307,Customer,1994,1
3,383,2018-09-01 09:44:46.0030,2018-09-01 09:51:09.9230,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,29261,Subscriber,1987,1
4,377,2018-09-01 09:44:46.1850,2018-09-01 09:51:03.6330,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,33665,Subscriber,1985,1

In [86]:
file10 = 'JC-201810-citibike-tripdata.csv'
df10 = pd.read_csv(file10)
df10.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df10.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,152,2018-10-01 07:44:41.4170,2018-10-01 07:47:14.2960,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,15302,Subscriber,1971,2
1,122,2018-10-01 08:50:05.4340,2018-10-01 08:52:08.2250,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29654,Subscriber,1973,1
2,211,2018-10-01 09:03:17.0640,2018-10-01 09:06:48.0940,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,33621,Subscriber,1958,1
3,342,2018-10-01 10:13:07.0090,2018-10-01 10:18:49.8960,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,26266,Subscriber,1982,1
4,2976,2018-10-01 10:45:14.2800,2018-10-01 11:34:51.2610,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,27083,Customer,1969,0

In [87]:
file11 = 'JC-201811-citibike-tripdata.csv'
df11 = pd.read_csv(file11)
df11.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df11.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1188,2018-11-01 06:32:27.5190,2018-11-01 06:52:15.9140,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,33662,Customer,1969,0
1,278,2018-11-01 07:14:31.8680,2018-11-01 07:19:10.2610,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29254,Subscriber,1963,1
2,115,2018-11-01 07:33:17.1920,2018-11-01 07:35:12.2830,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,33607,Subscriber,1966,1
3,155,2018-11-01 08:20:10.9320,2018-11-01 08:22:46.7050,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,29222,Subscriber,1975,2
4,82,2018-11-01 08:35:02.7850,2018-11-01 08:36:25.1840,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29678,Subscriber,1975,1

In [88]:
file12 = 'JC-201812-citibike-tripdata.csv'
df12 = pd.read_csv(file12)
df12.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df12.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,170,2018-12-01 00:03:53.3860,2018-12-01 00:06:43.7160,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,26261,Subscriber,1975,1
1,172,2018-12-01 00:47:13.7340,2018-12-01 00:50:05.8160,3183,Exchange Place,40.716247,-74.033459,3481,York St,40.716490,-74.041050,26175,Subscriber,1988,1
2,247,2018-12-01 00:48:57.6960,2018-12-01 00:53:05.6780,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29255,Subscriber,1990,1
3,406,2018-12-01 01:33:53.6630,2018-12-01 01:40:39.7480,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29275,Subscriber,1995,1
4,354,2018-12-01 06:26:52.5120,2018-12-01 06:32:46.5170,3183,Exchange Place,40.716247,-74.033459,3211,Newark Ave,40.721525,-74.046305,29658,Subscriber,1976,1

In [89]:
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12])
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1
5,613,2018-01-01 22:05:05.8740,2018-01-01 22:15:19.4190,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,31859,Subscriber,1982,1
6,290,2018-01-02 12:13:51.7940,2018-01-02 12:18:42.1070,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31694,Subscriber,1958,1
7,381,2018-01-02 12:50:03.3430,2018-01-02 12:56:24.6440,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,40.716540,-74.049638,31754,Subscriber,1989,2
8,318,2018-01-02 13:55:58.2430,2018-01-02 14:01:16.8810,3183,Exchange Place,40.716247,-74.033459,3275,Columbus Drive,40.718355,-74.038914,31816,Subscriber,1960,1
9,1852,2018-01-02 16:55:29.6390,2018-01-02 17:26:22.3050,3183,Exchange Place,40.716247,-74.033459,3281,Leonard Gordon Park,40.745910,-74.057271,31754,Subscriber,1976,1
10,460,2018-01-02 17:01:50.5860,2018-01-02 17:09:31.4340,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,33463,Subscriber,1989,2
11,403,2018-01-02 17:05:12.2360,2018-01-02 17:11:55.2630,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,40.716540,-74.049638,26256,Subscriber,1985,1
12,264,2018-01-02 17:05:12.6730,2018-01-02 17:09:37.4020,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29616,Subscriber,1974,1
13,282,2018-01-02 17:19:56.6090,2018-01-02 17:24:39.5340,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29681,Subscriber,1976,1
14,308,2018-01-02 17:31:45.9880,2018-01-02 17:36:54.3590,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31949,Subscriber,1968,1
15,561,2018-01-02 17:32:54.8400,2018-01-02 17:42:16.3140,3183,Exchange Place,40.716247,-74.033459,3269,Brunswick & 6th,40.726012,-74.050389,29591,Subscriber,1976,1
16,114,2018-01-02 17:37:44.3450,2018-01-02 17:39:38.8760,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31925,Subscriber,1988,1
17,302,2018-01-02 17:54:04.8770,2018-01-02 17:59:06.9730,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31777,Subscriber,1990,1
18,230,2018-01-02 17:58:24.6360,2018-01-02 18:02:15.6320,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31763,Subscriber,1992,1
19,596,2018-01-02 18:05:59.6240,2018-01-02 18:15:55.8590,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29662,Subscriber,1992,1
20,826,2018-01-02 18:10:58.8600,2018-01-02 18:24:45.1600,3183,Exchange Place,40.716247,-74.033459,3194,McGinley Square,40.725340,-74.067622,31765,Subscriber,1989,1
21,368,2018-01-02 18:13:41.8510,2018-01-02 18:19:49.9780,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31695,Subscriber,1985,1
22,291,2018-01-02 18:18:41.6860,2018-01-02 18:23:33.0620,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31934,Subscriber,1980,1
23,250,2018-01-02 18:20:06.1050,2018-01-02 18:24:16.1640,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31880,Subscriber,1995,1
24,199,2018-01-02 18:31:11.9870,2018-01-02 18:34:31.1880,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29623,Subscriber,1980,1
25,225,2018-01-02 18:38:50.5100,2018-01-02 18:42:36.2120,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,31691,Subscriber,1992,1
26,242,2018-01-02 18:41:29.5240,2018-01-02 18:45:32.3240,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26314,Subscriber,1981,0
27,214,2018-01-02 18:42:30.3030,2018-01-02 18:46:04.4630,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29581,Subscriber,1991,1
28,218,2018-01-02 19:29:20.7870,2018-01-02 19:32:59.1490,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31954,Subscriber,1991,1
29,318,2018-01-02 19:30:19.4880,2018-01-02 19:35:37.5450,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29615,Subscriber,1978,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20175,747,2018-12-10 20:33:10.0440,2018-12-10 20:45:37.2790,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29519,Subscriber,1958,1
20176,1124,2018-12-11 06:19:14.0610,2018-12-11 06:37:58.7960,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29657,Subscriber,1977,1
20177,648,2018-12-11 12:01:04.1040,2018-12-11 12:11:52.9080,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26287,Subscriber,1994,1
20178,575,2018-12-11 17:46:56.6360,2018-12-11 17:56:31.6520,3694,Jackson Square,40.711130,-74.078900,3191,Union St,40.718211,-74.083639,29239,Subscriber,1958,1
20179,961,2018-12-12 06:19:04.3900,2018-12-12 06:35:05.8390,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26247,Subscriber,1977,1
20180,2058,2018-12-12 09:09:44.0380,2018-12-12 09:44:02.7900,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,29641,Subscriber,1957,1
20181,640,2018-12-12 11:54:45.5290,2018-12-12 12:05:25.7630,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29641,Subscriber,1994,1
20182,934,2018-12-13 06:16:06.7510,2018-12-13 06:31:41.2170,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29681,Subscriber,1977,1
20183,703,2018-12-13 12:17:13.6280,2018-12-13 12:28:57.2350,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26190,Subscriber,1994,1
20184,936,2018-12-14 06:10:18.5060,2018-12-14 06:25:54.6120,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26155,Subscriber,1977,1
20185,668,2018-12-14 12:34:01.0310,2018-12-14 12:45:09.6550,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26312,Subscriber,1994,1
20186,645,2018-12-15 13:31:59.3590,2018-12-15 13:42:45.2030,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29224,Subscriber,1994,1
20187,1396,2018-12-15 16:28:38.1250,2018-12-15 16:51:54.9460,3694,Jackson Square,40.711130,-74.078900,3279,Dixon Mills,40.721630,-74.049968,29126,Subscriber,1988,2
20188,649,2018-12-16 11:55:07.8820,2018-12-16 12:05:57.4260,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29658,Subscriber,1994,1
20189,984,2018-12-17 06:26:18.2690,2018-12-17 06:42:42.9330,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26251,Subscriber,1977,1
20190,687,2018-12-17 12:18:47.1320,2018-12-17 12:30:14.5090,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29535,Subscriber,1994,1
20191,726,2018-12-17 17:38:45.4430,2018-12-17 17:50:52.4320,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29276,Subscriber,1973,2
20192,1041,2018-12-18 06:21:57.7450,2018-12-18 06:39:19.7440,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29221,Subscriber,1977,1
20193,654,2018-12-18 12:12:40.2980,2018-12-18 12:23:34.4020,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29300,Subscriber,1994,1
20194,1015,2018-12-19 06:15:11.2330,2018-12-19 06:32:06.2450,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26220,Subscriber,1977,1
20195,667,2018-12-19 11:39:50.4270,2018-12-19 11:50:58.2750,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29299,Subscriber,1994,1
20196,687,2018-12-20 13:28:39.0590,2018-12-20 13:40:06.6410,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29258,Subscriber,1994,1
20197,625,2018-12-21 12:05:04.3890,2018-12-21 12:15:29.5930,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29664,Subscriber,1994,1
20198,826,2018-12-21 16:34:37.2330,2018-12-21 16:48:24.0150,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,26306,Subscriber,1991,1
20199,640,2018-12-22 10:27:40.6590,2018-12-22 10:38:21.4170,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26298,Subscriber,1994,1
20200,1081,2018-12-22 11:51:46.0600,2018-12-22 12:09:47.4730,3694,Jackson Square,40.711130,-74.078900,3269,Brunswick & 6th,40.726012,-74.050389,29586,Subscriber,1993,1
20201,344,2018-12-25 21:40:09.8660,2018-12-25 21:45:54.2670,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,26241,Subscriber,1983,2
20202,1233,2018-12-29 12:55:45.9690,2018-12-29 13:16:19.5960,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29294,Subscriber,1988,1
20203,1057,2018-12-30 15:32:09.3320,2018-12-30 15:49:46.3510,3694,Jackson Square,40.711130,-74.078900,3213,Van Vorst Park,40.718489,-74.047727,29475,Subscriber,1991,2
20204,301,2018-12-31 16:34:11.9340,2018-12-31 16:39:13.8340,3694,Jackson Square,40.711130,-74.078900,3277,Communipaw & Berry Lane,40.714358,-74.066611,26270,Subscriber,1991,1

In [90]:
df.to_csv('citibike_2018.csv', sep = ',')

In [91]:
file_final = 'citibike_2018.csv'
df_final = pd.read_csv(file_final)
df_final

,Unnamed: 0,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1
1,1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2
2,2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1
3,3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1
4,4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1
5,5,613,2018-01-01 22:05:05.8740,2018-01-01 22:15:19.4190,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,31859,Subscriber,1982,1
6,6,290,2018-01-02 12:13:51.7940,2018-01-02 12:18:42.1070,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31694,Subscriber,1958,1
7,7,381,2018-01-02 12:50:03.3430,2018-01-02 12:56:24.6440,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,40.716540,-74.049638,31754,Subscriber,1989,2
8,8,318,2018-01-02 13:55:58.2430,2018-01-02 14:01:16.8810,3183,Exchange Place,40.716247,-74.033459,3275,Columbus Drive,40.718355,-74.038914,31816,Subscriber,1960,1
9,9,1852,2018-01-02 16:55:29.6390,2018-01-02 17:26:22.3050,3183,Exchange Place,40.716247,-74.033459,3281,Leonard Gordon Park,40.745910,-74.057271,31754,Subscriber,1976,1
10,10,460,2018-01-02 17:01:50.5860,2018-01-02 17:09:31.4340,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,33463,Subscriber,1989,2
11,11,403,2018-01-02 17:05:12.2360,2018-01-02 17:11:55.2630,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,40.716540,-74.049638,26256,Subscriber,1985,1
12,12,264,2018-01-02 17:05:12.6730,2018-01-02 17:09:37.4020,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29616,Subscriber,1974,1
13,13,282,2018-01-02 17:19:56.6090,2018-01-02 17:24:39.5340,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29681,Subscriber,1976,1
14,14,308,2018-01-02 17:31:45.9880,2018-01-02 17:36:54.3590,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31949,Subscriber,1968,1
15,15,561,2018-01-02 17:32:54.8400,2018-01-02 17:42:16.3140,3183,Exchange Place,40.716247,-74.033459,3269,Brunswick & 6th,40.726012,-74.050389,29591,Subscriber,1976,1
16,16,114,2018-01-02 17:37:44.3450,2018-01-02 17:39:38.8760,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31925,Subscriber,1988,1
17,17,302,2018-01-02 17:54:04.8770,2018-01-02 17:59:06.9730,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31777,Subscriber,1990,1
18,18,230,2018-01-02 17:58:24.6360,2018-01-02 18:02:15.6320,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31763,Subscriber,1992,1
19,19,596,2018-01-02 18:05:59.6240,2018-01-02 18:15:55.8590,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29662,Subscriber,1992,1
20,20,826,2018-01-02 18:10:58.8600,2018-01-02 18:24:45.1600,3183,Exchange Place,40.716247,-74.033459,3194,McGinley Square,40.725340,-74.067622,31765,Subscriber,1989,1
21,21,368,2018-01-02 18:13:41.8510,2018-01-02 18:19:49.9780,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31695,Subscriber,1985,1
22,22,291,2018-01-02 18:18:41.6860,2018-01-02 18:23:33.0620,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31934,Subscriber,1980,1
23,23,250,2018-01-02 18:20:06.1050,2018-01-02 18:24:16.1640,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31880,Subscriber,1995,1
24,24,199,2018-01-02 18:31:11.9870,2018-01-02 18:34:31.1880,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29623,Subscriber,1980,1
25,25,225,2018-01-02 18:38:50.5100,2018-01-02 18:42:36.2120,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717732,-74.043845,31691,Subscriber,1992,1
26,26,242,2018-01-02 18:41:29.5240,2018-01-02 18:45:32.3240,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26314,Subscriber,1981,0
27,27,214,2018-01-02 18:42:30.3030,2018-01-02 18:46:04.4630,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29581,Subscriber,1991,1
28,28,218,2018-01-02 19:29:20.7870,2018-01-02 19:32:59.1490,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31954,Subscriber,1991,1
29,29,318,2018-01-02 19:30:19.4880,2018-01-02 19:35:37.5450,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29615,Subscriber,1978,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353862,20175,747,2018-12-10 20:33:10.0440,2018-12-10 20:45:37.2790,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29519,Subscriber,1958,1
353863,20176,1124,2018-12-11 06:19:14.0610,2018-12-11 06:37:58.7960,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29657,Subscriber,1977,1
353864,20177,648,2018-12-11 12:01:04.1040,2018-12-11 12:11:52.9080,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26287,Subscriber,1994,1
353865,20178,575,2018-12-11 17:46:56.6360,2018-12-11 17:56:31.6520,3694,Jackson Square,40.711130,-74.078900,3191,Union St,40.718211,-74.083639,29239,Subscriber,1958,1
353866,20179,961,2018-12-12 06:19:04.3900,2018-12-12 06:35:05.8390,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26247,Subscriber,1977,1
353867,20180,2058,2018-12-12 09:09:44.0380,2018-12-12 09:44:02.7900,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,29641,Subscriber,1957,1
353868,20181,640,2018-12-12 11:54:45.5290,2018-12-12 12:05:25.7630,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29641,Subscriber,1994,1
353869,20182,934,2018-12-13 06:16:06.7510,2018-12-13 06:31:41.2170,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29681,Subscriber,1977,1
353870,20183,703,2018-12-13 12:17:13.6280,2018-12-13 12:28:57.2350,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26190,Subscriber,1994,1
353871,20184,936,2018-12-14 06:10:18.5060,2018-12-14 06:25:54.6120,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26155,Subscriber,1977,1
353872,20185,668,2018-12-14 12:34:01.0310,2018-12-14 12:45:09.6550,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26312,Subscriber,1994,1
353873,20186,645,2018-12-15 13:31:59.3590,2018-12-15 13:42:45.2030,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29224,Subscriber,1994,1
353874,20187,1396,2018-12-15 16:28:38.1250,2018-12-15 16:51:54.9460,3694,Jackson Square,40.711130,-74.078900,3279,Dixon Mills,40.721630,-74.049968,29126,Subscriber,1988,2
353875,20188,649,2018-12-16 11:55:07.8820,2018-12-16 12:05:57.4260,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29658,Subscriber,1994,1
353876,20189,984,2018-12-17 06:26:18.2690,2018-12-17 06:42:42.9330,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26251,Subscriber,1977,1
353877,20190,687,2018-12-17 12:18:47.1320,2018-12-17 12:30:14.5090,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29535,Subscriber,1994,1
353878,20191,726,2018-12-17 17:38:45.4430,2018-12-17 17:50:52.4320,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29276,Subscriber,1973,2
353879,20192,1041,2018-12-18 06:21:57.7450,2018-12-18 06:39:19.7440,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29221,Subscriber,1977,1
353880,20193,654,2018-12-18 12:12:40.2980,2018-12-18 12:23:34.4020,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29300,Subscriber,1994,1
353881,20194,1015,2018-12-19 06:15:11.2330,2018-12-19 06:32:06.2450,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26220,Subscriber,1977,1
353882,20195,667,2018-12-19 11:39:50.4270,2018-12-19 11:50:58.2750,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29299,Subscriber,1994,1
353883,20196,687,2018-12-20 13:28:39.0590,2018-12-20 13:40:06.6410,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29258,Subscriber,1994,1
353884,20197,625,2018-12-21 12:05:04.3890,2018-12-21 12:15:29.5930,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29664,Subscriber,1994,1
353885,20198,826,2018-12-21 16:34:37.2330,2018-12-21 16:48:24.0150,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,26306,Subscriber,1991,1
353886,20199,640,2018-12-22 10:27:40.6590,2018-12-22 10:38:21.4170,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26298,Subscriber,1994,1
353887,20200,1081,2018-12-22 11:51:46.0600,2018-12-22 12:09:47.4730,3694,Jackson Square,40.711130,-74.078900,3269,Brunswick & 6th,40.726012,-74.050389,29586,Subscriber,1993,1
353888,20201,344,2018-12-25 21:40:09.8660,2018-12-25 21:45:54.2670,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,26241,Subscriber,1983,2
353889,20202,1233,2018-12-29 12:55:45.9690,2018-12-29 13:16:19.5960,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29294,Subscriber,1988,1
353890,20203,1057,2018-12-30 15:32:09.3320,2018-12-30 15:49:46.3510,3694,Jackson Square,40.711130,-74.078900,3213,Van Vorst Park,40.718489,-74.047727,29475,Subscriber,1991,2
353891,20204,301,2018-12-31 16:34:11.9340,2018-12-31 16:39:13.8340,3694,Jackson Square,40.711130,-74.078900,3277,Communipaw & Berry Lane,40.714358,-74.066611,26270,Subscriber,1991,1